services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    command: suricata -c /etc/suricata/suricata.yaml -i eth0
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./suricata/config/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./suricata/rules:/var/lib/suricata/rules:ro
      - suricata-logs:/var/log/suricata
    restart: unless-stopped
    networks:
      - opensearch-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/templates:/usr/share/logstash/templates:ro
      - suricata-logs:/var/log/suricata:ro
      # Add access to other log sources
      - zeek-logs:/var/log/zeek:ro
      - ntopng-data:/var/log/ntopng:ro
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=maple-security-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "max_map_count=262144"
      # Enable ML plugins and features
      - "plugins.ml_commons.controller_enabled=true"
      - "plugins.ml_commons.mcp_server_enabled=true"
      - "plugins.ml_commons.only_run_on_ml_node=false"
      - "plugins.ml_commons.native_memory_threshold=99"
      # Index lifecycle management
      - "plugins.index_state_management.enabled=true"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    restart: unless-stopped

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      # Enable ML and Security Analytics plugins
      - "OPENSEARCH_DASHBOARDS_PLUGINS=anomalyDetectionDashboards,mlCommonsDashboards,securityAnalyticsDashboards"
    volumes:
      - ./opensearch-dashboards/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    depends_on:
      - opensearch
    networks:
      - opensearch-net
    restart: unless-stopped

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: admin-dashboard
    ports:
      - "3000:3000"
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - opensearch
      - logstash
    networks:
      - opensearch-net
    restart: unless-stopped

  # Network Traffic Analysis - WORKS OUT OF THE BOX
  ntopng:
    image: ntop/ntopng:stable
    container_name: ntopng
    command: --data-dir /var/lib/ntopng --interface eth0 --http-port 3001 --dont-change-user --syslog-facility local0
    cap_add:
      - NET_ADMIN
    ports:
      - "3001:3001"
    volumes:
      - ntopng-data:/var/lib/ntopng
      - ntopng-logs:/var/log/ntopng
    networks:
      - opensearch-net
    restart: unless-stopped

  # Network Protocol Analyzer - WORKS OUT OF THE BOX
  zeek:
    image: zeekurity/zeek:latest
    container_name: zeek
    command: zeek -i eth0 local "Site::local_nets += { 172.25.0.0/16 }"
    cap_add:
      - NET_ADMIN
    volumes:
      - zeek-logs:/usr/local/zeek/logs
    networks:
      - opensearch-net
    restart: unless-stopped



  # Honeypot - WORKS OUT OF THE BOX
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    ports:
      - "2222:2222/tcp"
      - "2223:2223/tcp"
    volumes:
      - cowrie-data:/cowrie/cowrie-git/var
    networks:
      - opensearch-net
    restart: unless-stopped

  # Vulnerability Scanner - ON DEMAND ONLY
  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: nuclei
    command: -version
    volumes:
      - nuclei-results:/results
    networks:
      - opensearch-net
    restart: "no"
    profiles:
      - scan

  # Port Scanner - ON DEMAND ONLY
  nmap:
    image: instrumentisto/nmap:latest
    container_name: nmap
    volumes:
      - nmap-results:/results
    networks:
      - opensearch-net
    restart: "no"
    profiles:
      - scan

volumes:
  suricata-logs:
  opensearch-data:
  ntopng-data:
  ntopng-logs:
  zeek-logs:
  cowrie-data:
  nuclei-results:
  nmap-results:

networks:
  opensearch-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16